name: 'Toml Select - TOML Field Extractor Action'
description: 'Reads a specified field from a TOML file and sets it as an output.'
author: 'Sylvan Ravinet'
inputs:
  file:
    description: 'The path to the TOML file.'
    required: true
  field:
    description: 'The field to extract from the TOML file.'
    required: true
outputs:
  value:
    description: 'The value of the specified field in the TOML file.'
runs:
  using: 'node20'
  main: 'dist/index.js'

branding:
  icon: 'search' # Choose an appropriate icon from https://feathericons.com/
  color: 'blue'
